version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/src
    command: sh -c "yarn db:migrate && yarn db:seed && yarn dev"
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      DB_USER: "$DB_USER"
      DB_PASSWORD: "$DB_PASSWORD"
      DB_NAME: "$DB_NAME"
      DB_HOST: db
      JWT_EXPIRY: "$JWT_EXPIRY"
      JWT_SECRET: "$JWT_SECRET"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
